#spring.application.name=demo
spring.application.name=productapp



# PostgreSQL setup (Cloud SQL)
spring.datasource.url=jdbc:postgresql://localhost/${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driverClassName=org.postgresql.Driver

# hibernate setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# hibernate setup
#Testing
#spring.jpa.hibernate.ddl-auto = create-drop
#Developement

#spring.jpa.hibernate.ddl-auto = validate
#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.open-in-view = false


#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
